import { Movie, MovieCategory, WeeklyRankingItem } from './types';

export const movieCategories: MovieCategory[] = [
  { id: 'all', name: '全部', value: 'all' },
  { id: 'drama', name: '剧情', value: 'drama' },
  { id: 'comedy', name: '喜剧', value: 'comedy' },
  { id: 'action', name: '动作', value: 'action' },
  { id: 'scifi', name: '科幻', value: 'scifi' },
  { id: 'animation', name: '动画', value: 'animation' },
  { id: 'romance', name: '爱情', value: 'romance' },
  { id: 'thriller', name: '惊悚', value: 'thriller' },
  { id: 'fantasy', name: '奇幻', value: 'fantasy' },
  { id: 'crime', name: '犯罪', value: 'crime' },
  { id: 'family', name: '家庭', value: 'family' },
  { id: 'war', name: '战争', value: 'war' },
  { id: 'history', name: '历史', value: 'history' },
  { id: 'western', name: '西部', value: 'western' },
  { id: 'musical', name: '歌舞', value: 'musical' },
  { id: 'sport', name: '运动', value: 'sport' },
  { id: 'documentary', name: '纪录片', value: 'documentary' },
  { id: 'short', name: '短片', value: 'short' },
  { id: 'adult', name: '情色', value: 'adult' },
  { id: 'gay', name: '同性', value: 'gay' },
];

export const mockMovies: Movie[] = [
  {
    id: '1',
    title: '死神来了6：血脉诅咒',
    poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=300&h=400&fit=crop',
    rating: 6.9,
    ratingCount: 57882,
    genres: ['惊悚', '科幻', '恐怖'],
    year: '2025',
    country: '法国 / 美国 / 中国大陆',
    directors: ['凯伦·琳'],
    actors: ['胡安娜', '特里克·希尔德', '乔伊·安德森'],
    description: '2025-05-14(法国) / 2025-05-16(美国) / 2025中国大陆',
    rank: 1,
    isHot: true
  },
  {
    id: '2',
    title: '惊变28年',
    poster: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300&h=400&fit=crop',
    rating: 7.1,
    ratingCount: 2639,
    genres: ['科幻', '惊悚', '恐怖'],
    year: '2025',
    country: '中国台湾 / 美国',
    directors: ['丹尼·博伊尔'],
    actors: ['杰克·奥康奈尔', '艾文·布雷纳'],
    description: '2025-06-18(中国台湾) / 2025-06-20(美国)',
    rank: 2
  },
  {
    id: '3',
    title: '罪人',
    poster: 'https://images.unsplash.com/photo-1489599807777-a5f6b6b7a7d7?w=300&h=400&fit=crop',
    rating: 7.7,
    ratingCount: 42291,
    genres: ['剧情', '犯罪'],
    year: '2025',
    country: '法国 / 美国',
    directors: ['迈克尔·曼'],
    actors: ['奥斯卡·伊萨克', '杰西卡·查斯坦'],
    description: '2025-04-16(法国) / 2025-04-18(美国)',
    rank: 3
  },
  {
    id: '4',
    title: 'F1：狂飙飞车',
    poster: 'https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=300&h=400&fit=crop',
    rating: 8.2,
    ratingCount: 15234,
    genres: ['动作', '运动', '剧情'],
    year: '2025',
    country: '美国 / 英国',
    directors: ['约瑟夫·科辛斯基'],
    actors: ['布拉德·皮特', '达米安·路易斯'],
    description: '2025-06-27更新',
    rank: 4,
    isHot: true
  },
  {
    id: '5',
    title: '新刺龙之子',
    poster: 'https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=300&h=400&fit=crop',
    rating: 6.8,
    ratingCount: 8956,
    genres: ['动作', '冒险'],
    year: '2025',
    country: '中国大陆',
    directors: ['张艺谋'],
    actors: ['易烊千玺', '张子枫'],
    description: '2025-07-15(中国大陆)',
    rank: 5
  },
  {
    id: '6',
    title: '线虫战士：余韵之王',
    poster: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?w=300&h=400&fit=crop',
    rating: 7.3,
    ratingCount: 23891,
    genres: ['科幻', '动作'],
    year: '2025',
    country: '美国',
    directors: ['丹尼斯·维伦纽瓦'],
    actors: ['提摩西·查拉梅', '赞达亚'],
    description: '2025-03-21(美国)',
    rank: 6
  },
  {
    id: '7',
    title: '罗马人帝国',
    poster: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=300&h=400&fit=crop',
    rating: 8.1,
    ratingCount: 67234,
    genres: ['历史', '战争', '剧情'],
    year: '2024',
    country: '美国 / 英国',
    directors: ['雷德利·斯科特'],
    actors: ['保罗·麦斯卡', '佩德罗·帕斯卡'],
    description: '2024-11-22(美国)',
    rank: 7
  },
  {
    id: '8',
    title: '名侦探柯南：血腥的追踪',
    poster: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300&h=400&fit=crop',
    rating: 7.9,
    ratingCount: 45672,
    genres: ['动画', '悬疑', '犯罪'],
    year: '2025',
    country: '日本',
    directors: ['山本泰一郎'],
    actors: ['高山南', '山崎和佳奈'],
    description: '2025-04-19(日本)',
    rank: 8
  }
];

export const weeklyRanking: WeeklyRankingItem[] = [
  { id: '1', title: 'F1：狂飙飞车', change: 10 },
  { id: '2', title: '新刺龙之子手', change: 1 },
  { id: '3', title: '线虫战士：余韵之王', change: 0 },
  { id: '4', title: '罪人', change: 2 },
  { id: '5', title: '但愿人长久', change: 6 },
  { id: '6', title: '大风起', change: 5 },
  { id: '7', title: '名侦探柯南：血腥的追踪', change: 4 },
  { id: '8', title: '死神来了6：血脉诅咒', change: 3 },
  { id: '9', title: '死神来了6：血脉诅咒', change: 2 },
  { id: '10', title: '制尼重计划', change: 1 }
]; 